module.exports = [
	{name: "Onkur Sen", 		section: "Top", 	position: "Music Director", 	sectionLeader: true},
	{name: "Rohit Prasanna", 	section: "Lead", 	position: "President", 			sectionLeader: true},
	{name: "Sandip Srinivas", 	section: "Bari", 	position: "Pitch Pipe", 		sectionLeader: true},
	{name: "David Jiang", 		section: "Bass", 	position: "???",			 	sectionLeader: true},
	{name: "Nikhil Goel", 		section: "Top"},
	{name: "Pranav Sriram", 	section: "Lead"},
	{name: "Suhas Suresha", 	section: "Bari"},
	{name: "Ronald Tep", 		section: "Bass"},
	{name: "Connor Holland", 	section: "Top"},
	{name: "Nathan Dalal", 		section: "Lead"},
	{name: "Jaydeep Singh", 	section: "Bari"},
	{name: "Ben Wu", 			section: "Bass"},
	{name: "Kuhan Jeyapragasan",section: "Top"},
	{name: "Bobby Pragada", 	section: "Lead"},
]